import psycopg2
conn = psycopg2.connect("dbname='alan' user='alan' host='localhost' password='alan'")
cur = conn.cursor()
cur.execute('DROP TABLE "pokemon";')  
conn.commit()
cur.execute('DROP TABLE "pokemontypechart";') 
conn.commit()
cur.execute('DROP TABLE "pokemonevolution";')
conn.commit()
cur.execute('DROP TABLE "animelist";') 
conn.commit()
cur.execute('DROP TABLE "filmylist";') 
conn.commit()
cur.execute('DROP TABLE "komputery";') 
conn.commit()
cur.execute('DROP TABLE "categories";') 
conn.commit()
cur.execute('DROP TABLE "customers";') 
conn.commit()
cur.execute('DROP TABLE "products";') 
conn.commit()
conn.close()
